title:  Setekhid's blog
author: Huitse Tai
email:  geb.1989@gmail.com
description: >
    This is my personal blog.

twitter_username: setekhid
github_username:  setekhid

google_analytics: UA-107725703-1
disqus:
    shortname: setesblog

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/
minima:
    date_format: "%b %-d, %Y"

plugins:
# feed.xml plugin
    - jekyll-feed

# Build settings
markdown: kramdown
theme: minima
exclude:
    - Gemfile
    - Gemfile.lock
